#!/bin/bash -x


# Base image:
# Raspberry Pi OS (Legacy)
# A port of Debian Buster with security updates and desktop environment
# Released: 2022-09-22


################################################################################
# Step 0: Raspi-Config
################################################################################


########################################
# Interfaces
########################################

# Enable SSH
# Enable VNC
# Enable SPI
# Enable I2C
# Enable Serial Port
# Enable Serial Console


########################################
# Localisation
########################################

# Set Locale
# Set Timezone
# Set WiFi Country


################################################################################
# Step 1: Install Required Libraries
################################################################################


########################################
# 1.A APT Packages
########################################

sudo apt update

# Declare list of package names and versions
declare -A apt_packages
apt_packages["git"]=1:2.20.1-2+deb10u4
apt_packages["python-smbus"]=4.1-1
apt_packages["python-pip"]=18.1-5+rpt1
apt_packages["python-pil"]=5.4.1-2+deb10u3
apt_packages["python-numpy"]=1:1.16.2-1
apt_packages["python-dev"]=2.7.16-1
apt_packages["python3-pip"]=18.1-5+rpt1
apt_packages["python3-pil"]=5.4.1-2+deb10u3
apt_packages["libjpeg8-dev"]=8d1-2
apt_packages["imagemagick"]=8:6.9.10.23+dfsg-2.1+deb10u1
apt_packages["libv4l-dev"]=1.16.3-3
apt_packages["libusb-dev"]=2:0.1.12-32
apt_packages["libftdi-dev"]=0.20-4
apt_packages["libftdi1-dev"]=1.4-1+b2
apt_packages["wiringpi"]=2.50
apt_packages["hostapd"]=2:2.7+git20190128+0c1e29f-6+deb10u3
apt_packages["dnsmasq"]=2.80-1+rpt1+deb10u1
apt_packages["libftdi-dev"]=0.20-4
apt_packages["mongodb"]=1:2.4.14-4
apt_packages["automake"]=1:1.16.1-4

# Loop through package list, install specified version, and lock to prevent accidental upgrades
for key in ${!apt_packages[@]}; do    	
	if [[ $(apt-cache policy ${key} | awk '/Installed: /{ print $2 }') != ${apt_packages[${key}]} ]]; then
		sudo apt-mark unhold ${key}
		sudo apt install ${key}=${apt_packages[${key}]} -y --allow-downgrades
		sudo apt-mark hold ${key}
	fi	
done

# Clean orphaned dependencies and cache
sudo apt autoremove -y
sudo apt autoclean -y


########################################
# 1.B Node.js
########################################

# Export and load nvm command for script use
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Verify/Install NVM (Node Version Manager)
if [[ $(nvm -v) != "0.39.1" ]]; then
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
fi

# Export and load nvm command for script use
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Verify/Install Node.js
if [[ $(node -v) != "v9.10.1" ]]; then
	nvm install 9.10.1
	nvm use 9.10.1
fi

# Declare symlinks
declare -A symlinks
symlinks["$NVM_DIR/versions/node/v9.10.1/bin/node"]=/usr/local/bin/node
symlinks["$NVM_DIR/versions/node/v9.10.1/bin/npm"]=/usr/local/bin/npm

# Loop through symlinks and create them if they don't already exist
for key in ${!symlinks[@]}; do
	if [ ! -L ${symlinks[${key}]} ] || [ ! -e ${symlinks[${key}]} ]; then
		sudo ln -s ${key} ${symlinks[${key}]}		
	fi
done


########################################
# 1.C: MyBot Software
########################################

if [ ! -d "/usr/Fusion" ]; then
	# Install software
	sudo git clone https://github.com/Modern-Robotics/Fusion.git /usr/Fusion --branch Recruit
	sudo npm --prefix /usr/Fusion/FusionServer/Build install --production
else
	# Update software
	sudo git --git-dir /usr/Fusion/.git --work-tree=/usr/Fusion reset --hard HEAD
	sudo git --git-dir /usr/Fusion/.git --work-tree=/usr/Fusion pull
	sudo npm --prefix /usr/Fusion/FusionServer/Build install --production
fi


########################################
# 1.D: PIP Packages
########################################

# Dynamically retrieve fusion driver path and version
fusion_driver_path=$(find /usr/Fusion/lib/ -name Fusion-*.tar.gz)
fusion_driver_version=$(find /usr/Fusion/lib/ -name Fusion-*.tar.gz | grep -Eo '[0-9]+\.[0-9]+\.[0-9]')

# An embedded python script used to retrieve a pip package's version
# Currently used because the traditional 'pip show (package)' command is too slow
find_pip_package_version="
import sys
import pkg_resources
try:
	dist = pkg_resources.get_distribution(sys.argv[1])
	print('{}'.format(dist.version))
except pkg_resources.DistributionNotFound:
	print('')
"

# Declare list of pip package names and versions
declare -A pip_packages
pip_packages["Fusion"]=$fusion_driver_version
pip_packages["remi"]=1.1
pip_packages["pylibftdi"]=0.17.0
pip_packages["RPi.GPIO"]=0.7.0
pip_packages["spidev"]=3.5

# Loop through package list, install specified version
for key in ${!pip_packages[@]}; do
	installedVersion=$(python -c "$find_pip_package_version" ${key})
	if [[ $installedVersion != ${pip_packages[${key}]} ]]; then
		# Fusion package is installed from local directory
		if [[ ${key} == "Fusion" ]]; then
			sudo pip install $fusion_driver_path
		else
			sudo pip install ${key}==${pip_packages[${key}]}
		fi
	fi
done

########################################
# 1.D: LCD Libraries
########################################

# Move LCD library for easier python import usage
if [ ! -d "/usr/lib/python2.7/dist-packages/lcddisplay" ]; then
    sudo cp -R /usr/Fusion/lib/LCD_Module_RPI_code/RaspberryPi/python/lib /usr/lib/python2.7/dist-packages/lcddisplay
fi


################################################################################
# Step 2: Edit Configuration Files
################################################################################


########################################
# 2.A: DHCPCD
########################################

if [ ! -f "/etc/dhcpcd.conf.orig" ]; then
    sudo mv /etc/dhcpcd.conf /etc/dhcpcd.conf.orig
	sudo cp /usr/Fusion/config/dhcpcd/dhcpcd.conf /etc/dhcpcd.conf
fi


########################################
# 2.B: DNSMASQ
########################################

if [ ! -f "/etc/dnsmasq.conf.orig" ]; then
	sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig
	sudo cp /usr/Fusion/config/dnsmasq/dnsmasq.conf /etc/dnsmasq.conf
fi


########################################
# 2.C: HOSTAPD
########################################

if [ ! -f "/etc/default/hostapd.orig" ]; then
	sudo mv /etc/default/hostapd /etc/default/hostapd.orig
	sudo cp /usr/Fusion/config/hostapd/hostapd /etc/default/hostapd
	sudo cp /usr/Fusion/config/hostapd/hostapd.conf /etc/hostapd/hostapd.conf
	sudo systemctl unmask hostapd.service
fi


########################################
# 2.C: HOSTS
########################################

if [ ! -f "/etc/hosts.orig" ]; then
	sudo mv /etc/hosts /etc/hosts.orig
	sudo cp /usr/Fusion/config/hosts /etc/hosts
fi


################################################################################
# Step 3: Configure Custom Services
################################################################################


########################################
# 3.A: APSTA
########################################

if [[ $(sudo systemctl is-active apsta.service) == "inactive" ]]; then
	sudo systemctl stop hostapd
	sudo systemctl stop dnsmasq
	sudo systemctl stop dhcpcd
	sudo systemctl disable hostapd
	sudo systemctl disable dnsmasq
	sudo systemctl disable dhcpcd
	sudo cp /usr/Fusion/bin/startDualNetworkMode /usr/local/bin/startDualNetworkMode
	sudo chmod 744 /usr/local/bin/startDualNetworkMode
	sudo cp /usr/Fusion/config/apsta.service /lib/systemd/system/apsta.service
	sudo chmod 644 /lib/systemd/system/apsta.service
	sudo systemctl daemon-reload
	sudo systemctl enable apsta.service
fi


########################################
# 3.B: Splashscreen
########################################

if [[ $(sudo systemctl is-active splashscreen.service) == "inactive" ]]; then
	sudo cp /usr/Fusion/config/splashscreen.service /lib/systemd/system/splashscreen.service
	sudo chmod 644 /lib/systemd/system/splashscreen.service
	sudo systemctl daemon-reload
	sudo systemctl enable splashscreen.service
fi


########################################
# 3.C: MyBot
########################################

if [[ $(sudo systemctl is-active mybot.service) == "inactive" ]]; then
	sudo cp /usr/Fusion/config/mybot.service /lib/systemd/system/mybot.service
	sudo chmod 644 /lib/systemd/system/mybot.service
	sudo systemctl daemon-reload
	sudo systemctl enable mybot.service
fi


################################################################################
# Step 4: Reboot
################################################################################

sudo reboot