#!/bin/bash -x


# Base image:
# Raspberry Pi OS (Legacy)
# A port of Debian Buster with security updates and desktop environment
# Released: 2023-02-21


################################################################################
# Preconfiguration: Raspi-Config
################################################################################


########################################
# Interfaces
########################################

# Enable SSH
# Enable VNC
# Enable SPI
# Enable I2C
# Enable Serial Port
# Enable Serial Console


########################################
# Localization
########################################

# Set Locale
# Set Timezone
# Set WiFi Country


################################################################################
# Step 0: Parameters
################################################################################


########################################
# Define Variables Default Values
########################################

branch=Recruit
version=HEAD


########################################
# Overide Variables Values If Supplied
########################################

while getopts c:s:p:b:v: flag
do
    case "${flag}" in
        b) branch=${OPTARG};;
        v) version=${OPTARG};;
    esac
done


################################################################################
# Step 1: Install Required Libraries
################################################################################


########################################
# 1.A APT Packages
########################################

# Declare list of package names and versions
declare -A apt_packages
apt_packages["git"]=1:2.20.1-2+deb10u7 							# 1:2.20.1-2+deb10u7
apt_packages["python-smbus"]=4.1-1								# 4.1-1
apt_packages["python-pip"]=18.1-5+rpt1							# 18.1-5+rpt1
apt_packages["python-pil"]=5.4.1-2+deb10u3						# 5.4.1-2+deb10u3
apt_packages["python-numpy"]=1:1.16.2-1							# 1:1.16.2-1
apt_packages["python-dev"]=2.7.16-1								# 2.7.16-1
apt_packages["python3-pip"]=18.1-5+rpt1							# 18.1-5+rpt1
apt_packages["python3-pil"]=5.4.1-2+deb10u3						# 5.4.1-2+deb10u3
apt_packages["wiringpi"]=2.50									# 2.50
apt_packages["libjpeg8-dev"]=8d1-2								# Not Installed
apt_packages["libv4l-dev"]=1.16.3-3								# Not Installed
apt_packages["libusb-dev"]=2:0.1.12-32							# Not Installed
apt_packages["libftdi-dev"]=0.20-4								# Not Installed
apt_packages["libftdi1"]=0.20-4									# Not Installed
apt_packages["libftdi1-dev"]=1.4-1+b2							# Not Installed
apt_packages["hostapd"]=2:2.7+git20190128+0c1e29f-6+deb10u3		# Not Installed
apt_packages["dnsmasq"]=2.80-1+rpt1+deb10u1						# Not Installed
apt_packages["mongodb"]=1:2.4.14-4								# Not Installed

# Loop through package list, install specified version, and lock to prevent accidental upgrades
apt_update_needed=false
apt_update_performed=false
for key in ${!apt_packages[@]}; do    	
	if [[ $(apt-cache policy ${key} | awk '/Installed: /{ print $2 }') != ${apt_packages[${key}]} ]]; then
		apt_update_needed=true
		if [ $apt_update_needed == true ] && [ apt_update_performed == false ]; then
			sudo apt update
			apt_update_performed=true
		fi
		sudo apt install ${key}=${apt_packages[${key}]} -y --allow-downgrades
	fi	
done

# Clean orphaned dependencies and cache if update performed
if [ $apt_update_performed == true ]; then
	sudo apt autoremove -y
	sudo apt autoclean -y
fi


########################################
# 1.B Node.js
########################################

# Verify/Install NVM (Node Version Manager)
if [[ $(n -V) != "v9.0.1" ]]; then
	sudo curl -L https://raw.githubusercontent.com/tj/n/v9.0.1/bin/n -o /usr/local/bin/n
	sudo chmod 755 /usr/local/bin/n
fi

# Verify/Install Node.js
if [[ $(node -v) != "v9.10.1" ]]; then
	sudo n 9.10.1
fi


########################################
# 1.C: MyBot Software
########################################

if [ ! -d "/usr/Fusion" ]; then
	# Install software
	sudo git clone https://github.com/Modern-Robotics/Fusion.git /usr/Fusion --branch ${branch}
	sudo npm --prefix /usr/Fusion/FusionServer/Build install --production
else
	# Update software
	sudo git --git-dir /usr/Fusion/.git --work-tree=/usr/Fusion reset --hard HEAD
	sudo git --git-dir /usr/Fusion/.git --work-tree=/usr/Fusion pull
	sudo npm --prefix /usr/Fusion/FusionServer/Build install --production
fi


########################################
# 1.D: PIP Packages
########################################

# An embedded python script used to retrieve a pip package's version
# Currently used because the traditional 'pip show (package)' command is too slow
find_pip_package_version="
import sys
import pkg_resources
try:
	dist = pkg_resources.get_distribution(sys.argv[1])
	print('{}'.format(dist.version))
except pkg_resources.DistributionNotFound:
	print('')
"

# Declare list of pip package names and versions
declare -A pip_packages
pip_packages["remi"]=1.1
pip_packages["pylibftdi"]=0.17.0
pip_packages["RPi.GPIO"]=0.7.0
pip_packages["spidev"]=3.5

# Loop through package list, install specified version
for key in ${!pip_packages[@]}; do
	installedVersion=$(python -c "$find_pip_package_version" ${key})
	if [[ $installedVersion != ${pip_packages[${key}]} ]]; then		
		sudo pip install ${key}==${pip_packages[${key}]}
	fi
done

# Declare an array to store custom pip packages' versions'
declare -A custom_pip_packages

# Declare an array to store custom pip packages' paths
declare -A custom_pip_packages_paths

# Loop through all files in the lib directory searching for custom packages
for file in /usr/Fusion/lib/*; do

  # If the file ends with .tar.gz, add it to custom packages
  if [[ $file == *.tar.gz ]]; then

    # Extract the name and version
    fileName=$(basename "$file" .tar.gz)
    packageName=$(echo "$fileName" | grep -oP '^[^-]+')
    packageVersion=$(echo "$file" | grep -oP '(?<=-)\d+\.\d+\.\d+')

    custom_pip_packages[$packageName]="$packageVersion"
    custom_pip_packages_paths[$packageName]="$file"

  fi
done


# Loop through custom package list, install specified version
for package in ${!custom_pip_packages[@]}; do
    installedVersion=$(python -c "$find_pip_package_version" ${key})
    if [[ $installedVersion != ${custom_pip_packages[${package}]} ]]; then
        sudo pip install ${custom_pip_packages_paths[${package}]}
    fi
done


########################################
# 1.D: Pygame
########################################

# Modify pygame library to disable welcome messages
sudo sed -i "s|^print('pygame %s' % ver)|# &|" /usr/lib/python2.7/dist-packages/pygame/__init__.py
sudo sed -i "s|^print('Hello from the pygame community. https://www.pygame.org/contribute.html')|# &|" /usr/lib/python2.7/dist-packages/pygame/__init__.py


########################################
# 1.E: LCD Libraries
########################################

# Move LCD library for easier python import usage
if [ ! -d "/usr/lib/python2.7/dist-packages/lcddisplay" ]; then
    sudo cp -R /usr/Fusion/lib/LCD_Module_RPI_code/RaspberryPi/python/lib /usr/lib/python2.7/dist-packages/lcddisplay
fi


################################################################################
# Step 2: Configuration Files
################################################################################


########################################
# 2.A: DHCPCD
########################################

# Installs DHCPCD config
if ! cmp -s /etc/dhcpcd.conf /usr/Fusion/config/dhcpcd/dhcpcd.conf; then
	sudo mv /etc/dhcpcd.conf /etc/dhcpcd.conf.orig
	sudo cp /usr/Fusion/config/dhcpcd/dhcpcd.conf /etc/dhcpcd.conf
fi


########################################
# 2.B: DNSMASQ
########################################

# Installs DNSMSQ config
if ! cmp -s /etc/dnsmasq.conf /usr/Fusion/config/dnsmasq/dnsmasq.conf; then
	sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig
	sudo cp /usr/Fusion/config/dnsmasq/dnsmasq.conf /etc/dnsmasq.conf
fi


########################################
# 2.C: HOSTAPD
########################################

# Installs HOSTAPD default config
if ! cmp -s /etc/default/hostapd /usr/Fusion/config/hostapd/hostapd; then
	sudo mv /etc/default/hostapd /etc/default/hostapd.orig
	sudo cp /usr/Fusion/config/hostapd/hostapd /etc/default/hostapd
fi

# Installs HOSTAPD config
# Must undo sed changes for proper comparison?
if ! cmp -s /etc/hostapd/hostapd.conf /usr/Fusion/config/hostapd/hostapd.conf; then
	sudo cp /usr/Fusion/config/hostapd/hostapd.conf /etc/hostapd/hostapd.conf
	sudo systemctl unmask hostapd.service
fi

# if [ ! -f "/etc/default/hostapd.orig" ]; then
# 	sudo mv /etc/default/hostapd /etc/default/hostapd.orig
# 	sudo cp /usr/Fusion/config/hostapd/hostapd /etc/default/hostapd
# 	sudo cp /usr/Fusion/config/hostapd/hostapd.conf /etc/hostapd/hostapd.conf
# 	# sudo sed -i 's|^channel=.*$|channel='"${channel}"'|g' /etc/hostapd/hostapd.conf
# 	# sudo sed -i 's|^ssid=.*$|ssid='"${ssid}"'|g' /etc/hostapd/hostapd.conf
# 	# sudo sed -i 's|^wpa_passphrase=.*$|wpa_passphrase='"${wpa_passphrase}"'|g' /etc/hostapd/hostapd.conf
# 	sudo systemctl unmask hostapd.service
# fi


################################################################################
# Step 3: Custom Services
################################################################################


########################################
# 3.A: APSTA Service
########################################

# Installs bash script
if ! cmp -s /usr/local/bin/startDualNetworkMode /usr/Fusion/bin/startDualNetworkMode; then
	sudo cp /usr/Fusion/bin/startDualNetworkMode /usr/local/bin/startDualNetworkMode
	sudo chmod 755 /usr/local/bin/startDualNetworkMode
fi

# Installs unit file
if ! cmp -s /lib/systemd/system/apsta.service /usr/Fusion/config/apsta.service; then
	sudo systemctl stop hostapd
	sudo systemctl stop dnsmasq
	sudo systemctl stop dhcpcd
	sudo systemctl disable hostapd
	sudo systemctl disable dnsmasq
	sudo systemctl disable dhcpcd
	sudo cp /usr/Fusion/config/apsta.service /lib/systemd/system/apsta.service
	sudo chmod 644 /lib/systemd/system/apsta.service
	sudo systemctl daemon-reload
	sudo systemctl enable apsta.service
fi


########################################
# 3.B: Splashscreen Service
########################################

# Installs unit file
if ! cmp -s /lib/systemd/system/splashscreen.service /usr/Fusion/config/splashscreen.service; then
	sudo cp /usr/Fusion/config/splashscreen.service /lib/systemd/system/splashscreen.service
	sudo chmod 644 /lib/systemd/system/splashscreen.service
	sudo systemctl daemon-reload
	sudo systemctl enable splashscreen.service
fi


########################################
# 3.C: MyBot Service
########################################

# Installs unit file
if ! cmp -s /lib/systemd/system/mybot.service /usr/Fusion/config/mybot.service; then
	sudo cp /usr/Fusion/config/mybot.service /lib/systemd/system/mybot.service
	sudo chmod 644 /lib/systemd/system/mybot.service
	sudo systemctl daemon-reload
	sudo systemctl enable mybot.service
fi


########################################
# 3.C: Sync Serial Service
########################################

# Installs bash script
if ! cmp -s /usr/local/bin/syncSerial /usr/Fusion/bin/syncSerial; then
	sudo cp /usr/Fusion/bin/syncSerial /usr/local/bin/syncSerial
	sudo chmod 755 /usr/local/bin/syncSerial
fi

# Installs unit file
if ! cmp -s /lib/systemd/system/syncserial.service /usr/Fusion/config/syncserial.service; then
	sudo cp /usr/Fusion/config/syncserial.service /lib/systemd/system/syncserial.service
	sudo chmod 644 /lib/systemd/system/syncserial.service
	sudo systemctl daemon-reload
	sudo systemctl enable syncserial.service
fi


########################################
# 3.C: Power off Board Service
########################################

# Installs bash script
if ! cmp -s /usr/local/bin/powerOffBoard /usr/Fusion/bin/powerOffBoard; then
	sudo cp /usr/Fusion/bin/powerOffBoard /usr/local/bin/powerOffBoard
	sudo chmod 755 /usr/local/bin/powerOffBoard
fi

# Installs unit file
if ! cmp -s /lib/systemd/system/poweroffboard.service /usr/Fusion/config/poweroffboard.service; then
	sudo cp /usr/Fusion/config/poweroffboard.service /lib/systemd/system/poweroffboard.service
	sudo chmod 644 /lib/systemd/system/poweroffboard.service
	sudo systemctl daemon-reload
	sudo systemctl enable poweroffboard.service
	sudo systemctl start poweroffboard.service
fi


################################################################################
# Step 4: Poweroff
################################################################################

reboot